version: '3.8'
services:
  mongodb_container:
    image: mongo
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
